project:
  type: website

website:
  title: "CITOverso"
  description: "Asesoría Científica y Análisis Computacional en Citometría de Flujo"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre mí
      - href: cursos.qmd
        text: Cursos
      - href: servicios.qmd
        text: Servicios de Asesoría
      - href: tutoriales.qmd
        text: Tutoriales en R
    right:
      - icon: github
        href: https://github.com/jvillanuevatoledo/citoverso
      - icon: linkedin
        href: https://linkedin.com/in/jvillanuevat
      - icon: envelope
        href: mailto:jvillanuevatoledo@gmail.com
      # Aquí agregaremos más adelante páginas como "Servicios" o "Blog"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
